### ISSUE TITLE
Readme refers to outdated facts

### ISSUE THREAD

**Issue by Pehrsons** [webrtc/KITE#1]
Regarding this line in the readme:

> **Attention:**  WebDriver for Firefox on Windows has some limitations (not supporting testing involving using media, or Firefox profile with fake media stream)

Did you file bugs for these? If so, what were their numbers? If not, please do so at https://bugzilla.mozilla.org/ so they can be fixed.

The former ("not supporting testing involving using media") would be useful to get some data on.

The latter ("Firefox profile with fake media stream") should be fixed in Firefox 57 by https://bugzilla.mozilla.org/show_bug.cgi?id=1390521 (released in November).

**Comment by agouaillard-cosmo** [comment]
Thank you for spotting this.

This refers to *some webdriver bindings* having this problem, not firefox webdriver binary itself. We had opened bugs against the different projects and verified our claim. We will update the Readme, and the Wiki accordingly to provide more accurate, and updated informations.
