### ISSUE TITLE
After updating the Kite framework I am getting kite-jar-with-dependencies.jar file is missing

### ISSUE THREAD

**Issue by kavyasetty456** [webrtc/KITE#114]
Hii,

 I updated the the Kite framework and after updating i am unable to run my code as it is saying please edit the file and set the KITE_Jar to the correct path

Can you please suggest me what are the things i have to edit and why kite-jar-with-dependencies.jar is missing after upda
![jar file missing](https://user-images.githubusercontent.com/54302175/80224303-25abf000-8667-11ea-9779-fbe83e8792b2.png)
ting.

I also attached screenshot please look into that 

Thank You.

**Comment by namvuCosmo** [comment]
Hi,

After compiling, do you have `kite-jar-with-dependencies.jar` at `%KITE_HOME%/KITE-Engine/target?

Can you also show me what you have in your D:\KITE-2-0\KITE?

**Comment by kavyasetty456** [comment]
Yes I understood that kite-jar-with-dependencies.jar file is missing in my %KITE_HOME%/KITE-Engine/target folder. After adding the jar file to the respective folder it worked fine until and unless if I  run with out compiling. If I compile then again the jar file is deleting. Can you please suggest me any solution?

Thank You.

**Comment by namvuCosmo** [comment]
I can't reproduce your issue. Can you list down the steps to reproduce it? What changes have you made to the project?

I just clone KITE on a new VM and compile it, I could still see the kite-jar-with-dependencies.jar in the folder.

I can't suggest you anything without knowing what the problem is.

**Comment by kavyasetty456** [comment]
Hii,

I can not say the exact reason. I just cloned KITE framework and added my project in Kite-base Pom.xml. Here I can see kite-jar-with-dependencies.jar in target folder but if I compile then kite-jar-with-dependencies.jar file is cleaning automatically.

![maven compiler plugin](https://user-images.githubusercontent.com/54302175/80668278-1261b000-8abf-11ea-8f29-316c0170c347.png)

**Comment by namvuCosmo** [comment]
Is there any reason that you have to clone kite-framework module alone?

**Comment by kavyasetty456** [comment]
No, I haven't clone only kite-framework. I updated complete Kite

**Comment by A-nguyenv** [comment]
Hi,
I cloned your JoinBackup repo on a new VM and managed to compile perfectly, with kite-jar-with-dependencies included. 
We can see on your screenshot that your KITE-Engine is not compiled, 0.7s shows it.
May we know what changes you did to the poms so we can try to reproduce?

**Comment by kavyasetty456** [comment]
Just now i cloned my project in other system everything is working fine after compilation also but when it comes to my system the same thing is happening every time.  Is this related to any system configuration?
And in Pom.xml i just added my project module that's it.

<modules>
    <module>KITE-Framework</module>
    <module>join</module>
    <module>KITE-Engine</module>
    <module>KITE-Example-Test</module>
    <module>KITE-AppRTC-Test</module>
    <module>KITE-WPT-Test</module>
  </modules>

**Comment by namvuCosmo** [comment]
It should not have anything to do with system configuration.

On your system it was working before?

Can you check if the maven version on 2 systems are different?

Just in case it's some existing dependencies problem, can you run `c -U` or `mvn -DskipTests clean install -U` to update the dependency list?
