### ISSUE TITLE
Need some clarification

### ISSUE THREAD

**Issue by ImranTelebu** [webrtc/KITE#115]
Below mentioned are few queries, I need clarity with. 
1. Can we use webrtc Get stats, which is available in KITE in SFU mode If yes then how can we fetch all the stats for the connected particular user and does it needs any prerequisites. 
2. Can we test Mute/Unmute, video pause/play features with the help of KITE.? 
    example: when I mute/pause myself how do I validate if I am actually muted/paused.

**Comment by agouaillard-cosmo** [comment]
KITE is helping instrumenting your client. If your client has a feature, then KITE can use it.
KITE can then capture the content of some UI element, and of some JS object or console for web app.

1. in a web app, if your peerconnection object is available globally, KITE can call its GetStats() methods and pool it for you. In a native app, if your native app call getStats and put the result as text in a UI element (that element does not need to e visible), then KITE can get the content of the element for you.

2. KITE is an instrumentation tool. if there is a way, through the app, to check something, then KITE can AUTOMATE it for you. It is not creating new feature.
for mute and unmute, if there is a corresponding event, KITE can check if the event is fired.  If there is a status variable, kite can check it for you. If you want to check the media, kite provides a little JS code that capture a frame from the video element and check if it s black, or pipe the audio to web audio, and check there is audio flowing. 

So, KITE is an INSTRUMENTATION, and AUTOMATION framework. It does not provide extra feature that are not already in teh app or the browser per say.
