### ISSUE TITLE
Attachments files name KO for JS

### ISSUE THREAD

**Issue by StephaneC** [webrtc/KITE#120]
Looks like, as statusDetails, the attachment name for the files are not read Java part. 
It's correctly set from javascript (present in temp/result.json) but not in kite-allure-reports.

**Comment by StephaneC** [comment]
Code to add in JSRunnerTest:
```
                String name = attachmentJSON.getString("name");
                reporter.textAttachment(stepReport, name, text, extension);
```
[PR submitted](https://github.com/webrtc/KITE/pull/121)

**Comment by namvuCosmo** [comment]
PR merged
