### ISSUE TITLE
Installation on Linux: grid-utils-0.0.1.jar not found

### ISSUE THREAD

**Issue by Sigma721** [webrtc/KITE#123]
Hi 

I am trying to install Kite on Ubuntu 18. I am getting this error and cannot find an alternative link to the required file:

wget https://github.com/CoSMoSoftware/KITE-Extras/releases/download/0.1.65/grid-utils-0.0.1.jar
Resolving github.com (github.com)... 140.82.118.3
Connecting to github.com (github.com)|140.82.118.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-05-13 11:06:29 ERROR 404: Not Found.

Any ideas?

**Comment by namvuCosmo** [comment]
Hi,

This file is no longer available there.

Why is this file required for the set up of KITE?

Can you please provide the step to reproduce this error?

**Comment by Sigma721** [comment]
Hi
I am following this in order to get KITE installed so that I can start running stress tests on my Janus server: https://github.com/webrtc/KITE/blob/master/README.md

I installed Java 8 and MVN, confirmed by output of "**mvn -version**" being as follows:
**_Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/teamroot/apache-maven-3.6.3
Java version: 1.8.0_252, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.3.0-1020-azure", arch: "amd64", family: "unix"_**

Then when pulling KITE and trying to run the configureLinux.sh I get the error.
1. mkdir GitHub
2. cd GitHub
3. git clone https://github.com/webrtc/KITE.git
4.cd KITE
5. **./configureLinux.sh**
 > Do you want to  install the local grid now? (y/n) **y**
 > Would you like to run the script with those configuration? (y/n/q)**n**
 >Would you like to install the browsers? (y/n/q)**y**
 >Would you like to use the capability Matcher? (y/n/q)**y**
 >Please check the corresponding KITE-Extras version from:
    https://github.com/CoSMoSoftware/KITE-Extras/releases
    currently the config file has the following versions:
    KITE_EXTRAS_VERSION=0.1.65
    GRID_UTILS_VERSION=0.0.1
    Are those versions correct? (y/n/q)**y**
 >Would you like to use a desktop Environment  or to run without any display? (y/n/q)**n** *_This is 
    Ubuntu Server 18_
 >Would you like to use 'localhost' as the hub address (instead of the IP)?  (y/n/q)**y**
 >Please check that the versions of Chrome match the one in the config file.
    currently the config file has the following version:
    CHROME_VERSION=81
    Is this version correct? (y/n/q)**y**
 >Please check that the versions of Firefox match the one in the config file.
    currently the config file has the following version:
    FIREFOX_VERSION=76
    Is this version correct? (y/n/q)**y**
>Please check the corresponding chromedriver version from:
    http://chromedriver.chromium.org/downloads
    currently the config file has the following version:
    CHROMEDRIVER_VERSION=81.0.4044.69
    Is this version correct? (y/n/q)**y**
 >Please check the corresponding geckodriver version from:
    https://github.com/mozilla/geckodriver/releases
    currently the config file has the following version:
    GECKO_VERSION=v0.26.0
    Is this version correct? (y/n/q)**y**
 >Please check the corresponding selenium version from:
    https://selenium-release.storage.googleapis.com/
    currently the config file has the following version:
    SELENIUM_VERSION_SHORT=3.141
    SELENIUM_VERSION=3.141.59
    Are those versions correct? (y/n/q)**y**
 >Do you want to start the Grid (y/n)?  **y**

**Comment by namvuCosmo** [comment]
Hi, sorry for the late reply. This is an error on our part, we will remove that in the next update.

For now, you can remove the download line in the script file `scripts/linux/path/installSelenium`:

```
...
wget https://selenium-release.storage.googleapis.com/$SELENIUM_VERSION_SHORT/selenium-server-standalone-$SELENIUM_VERSION.jar
#if [[ "$USE_CAPABILITY_MATCHER" = "TRUE" ]]
#then
#  wget https://github.com/CoSMoSoftware/KITE-Extras/releases/download/$KITE_EXTRAS_VERSION/grid-utils-$GRID_UTILS_VERSION.jar
#fi
#mv grid-utils-$GRID_UTILS_VERSION.jar grid.jar
#mv grid.jar ../../localGrid/hub

mv selenium-server-standalone-$SELENIUM_VERSION.jar selenium.jar
...
```
