### ISSUE TITLE
Capture network Performance Data Using BrowserMob Proxy

### ISSUE THREAD

**Issue by ImranTelebu** [webrtc/KITE#126]
Hi Kite team,
I just want to know that does kite has any feature to capture network performance data. if yes let me know.
For network data, I am trying to use browserMob proxy  (Third-party). which provide HAR file that has all network call-related data. But when I am using dependency of browserMob in Kite framework it gives me invalid signature error on runtime.
Please look into it. Thanks for considering
![network_error](https://user-images.githubusercontent.com/51738071/83142403-14467f80-a10e-11ea-92c5-4696f924e416.PNG)

dependency
https://mvnrepository.com/artifact/net.lightbody.bmp/browsermob-core/2.1.5

Thanks
Imran

**Comment by namvuCosmo** [comment]
Hi,

Currently any network performance data that KITE tests collect is coming from statistics provided by the peer connection itself, including but not limited to:
- bitrates
- framrates
- packet loss
- jitter 
- RTT

For this particular tool (browserMob proxy) I think I saw this error when I tried this before. I'll revisit this a see if I get this again. In any cases, can you tell me how you are implementing this in KITE framework?

**Comment by namvuCosmo** [comment]
For this exception, you can take a look here: 
 - https://stackoverflow.com/questions/34855649/invalid-signature-file-digest-for-manifest-main-attributes-exception-while-tryin
- https://vispud.blogspot.com/2019/03/exception-in-thread-main.html

![image](https://user-images.githubusercontent.com/27989546/83216497-faec1480-a19b-11ea-936b-acdbc5bbcd6d.png)

This will make the exception go away, but how to use this proxy is up to you.

**Comment by ImranTelebu** [comment]
Hi, 
I tried what you suggested. It worked for me., but after using this dependency I am not able to hit the URL. it gives me your connection is not secure, I tried multiple times, but it didn't work. If I get any solution in future will share complete implementation with you
