### ISSUE TITLE
Missing API documentation

### ISSUE THREAD

**Issue by Lazarus404** [webrtc/KITE#128]
I'd like to use this to test a number of systems in my organisation.  I am NOT a Java developer :-)

As such, what I need is the JS API documentation.  I've attempted to find the TestUtils Java class, so I can gleam potential API calls from that, but assume this must reside in a separate repo.

Is there a good place to start to find the API calls available to me in the tests?

**Comment by namvuCosmo** [comment]
Hi, 

Sorry we are a bit lacking in the documentation department, and the JS code is quite limited comparing to the java code. 

Most of KITE's JS code is in the kite-common library, which you can find here : https://www.npmjs.com/package/kite-common

In the `util` package you'll find the code for the case test class along with other things:
![image](https://user-images.githubusercontent.com/27989546/84220509-8bfcad00-ab05-11ea-858e-dcb506e230d2.png)
