### ISSUE TITLE
not found kite-framework 1.0.14

### ISSUE THREAD

**Issue by xieyugui** [webrtc/KITE#132]
<kite.framework.version>1.0.14</kite.framework.version>  not found

[WARNING] The POM for org.webrtc.kite:kite-framework:jar:1.0.14 is missing, no dependency information available
Downloading from jitpack.io: https://jitpack.io/org/webrtc/kite/kite-framework/1.0.14/kite-framework-1.0.14.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/webrtc/kite/kite-framework/1.0.14/kite-framework-1.0.14.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:09 min
[INFO] Finished at: 2020-06-19T15:41:23+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project example-test: Could not resolve dependencies for project org.webrtc.kite:example-test:jar:0.0.1: Could not find artifact org.webrtc.kite:kite-framework:jar:1.0.14 in jitpack.io (https://jitpack.io) -> [Help 1]

**Comment by namvuCosmo** [comment]
Hello,

Did you compile in the KITE's main directory (this will compile the engine, the framework along with all the test included) before this step?

**Comment by xieyugui** [comment]
get, it's my wrong,thanks
