### ISSUE TITLE
kite-common window size

### ISSUE THREAD

**Issue by Lazarus404** [webrtc/KITE#138]
I think, in the recent update (1.14), the window-size parameter is wrong.  The config shows up in `capabilities.capability`, while the lib is looking in `capabilities`

**Comment by namvuCosmo** [comment]
Hi, sorry for the super late reply, but I don't currently have the bandwidth to look into this. I'll do it when I can.

**Comment by Lazarus404** [comment]
I've added a PR for this in the `kite-common` repo.  Once that's updated, I've also created a branch for KITE with a Dockerfile that should work.  I need to do a little cleanup, but added a PR anyway for your perusal.
