### ISSUE TITLE
Can i write a new KIte Test in Python language using the Kite framework?

### ISSUE THREAD

**Issue by Richab23** [webrtc/KITE#139]
Hi,
I have tested a basic jitsi test using Java classes. I was able to get the stats using a fake video file. The same test i want to do in Python. Will i be able to use the Same KITE classes in Python?

**Comment by namvuCosmo** [comment]
Hi,

Sorry but we don't have support for Python, KITE can support fully in Java, and in a more limited manner, JavaScript.

**Comment by Richab23** [comment]
Ok. Thanks.
