### ISSUE TITLE
Compile fail during download kite-framework from maven

### ISSUE THREAD

**Issue by microelec** [webrtc/KITE#144]
Hello,

I just follow the instruction step by step. And it failed when compile KITE-Example-Test.
I am new to java/js world. why it is trying to download kite-framework from maven? As I already clone the whole project and the KITE\KITE-Engine is there. Any step I missed or environment setting wrong?
System avariables $mvn $path $KITE_HOME are set correctly, BTW.

=================================
Downloaded from central-repos: https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.jar (27 kB at 50 kB/s)
Downloading from central-repos: https://repo1.maven.org/maven2/org/webrtc/kite/kite-framework/1.0.15/kite-framework-1.0.15.pom
[WARNING] The POM for org.webrtc.kite:kite-framework:jar:1.0.15 is missing, no dependency information available
Downloading from central-repos: https://repo1.maven.org/maven2/org/webrtc/kite/kite-framework/1.0.15/kite-framework-1.0.15.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.528 s
[INFO] Finished at: 2020-07-03T17:10:23+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project example-test: Could not resolve dependencies for project org.webrtc.kite:example-test:jar:0.0.1: Could not find artifact org.webrtc.kite:kite-framework:jar:1.0.15 in central-repos (https://repo1.maven.org/maven2/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by namvuCosmo** [comment]
Hello,

Have you compile the whole project from KITE_HOME before compiling the test?

**Comment by microelec** [comment]
> Hello,
> 
> Have you compile the whole project from KITE_HOME before compiling the test?

Sooooo quick response! 
Compile the whole project and the results: failed here.
[ERROR] Failed to execute goal on project kite-framework: Could not resolve dependencies for project org.webrtc.kite:kite-framework:jar:1.0.15: Failure to find com.github.CoSMoSoftware:kite-extras:jar:0.1.69 in https://maven.aliyun.com/repository/public was cached in the local repository, resolution will not be reattempted until the update interval of aliyunmaven has elapsed or updates are forced -> [Help 1]

**Comment by namvuCosmo** [comment]
I just tried to compile again and it's working for me.

Do you have the latest code?

Can you please upload the pom.xml here so that I can check whether it's correct?

**Comment by microelec** [comment]
[

](url)

**Comment by microelec** [comment]
40239dae9571061b635f3404cda660e6dc72ed55
I clone it today. now i am trying your 1.01.
