### ISSUE TITLE
unable to automate test case in firefox with fake mp4 video

### ISSUE THREAD

**Issue by RajathTester** [webrtc/KITE#147]
Hi when trying to automate kite testcase with fake mp4 video for firefox client getting a 403 forbidden access error.

2020-07-15 19:17:29,857 INFO  - kiteServerCommand => http://localhost:8080/KITEServer/command?id=null&ip=localhost&cmd=play%20D:/desktop/Progress/FakeVideos/IVSAVideoV02.mp4%20&
 2020-07-15 19:17:30,533 ERROR - java.io.IOException: Server returned HTTP response code: 403 for URL: http://localhost:8080/KITEServer/command?id=null&ip=localhost&cmd=play%20D:/desktop/Progress/FakeVideos/IVSAVideoV02.mp4%20&
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at io.cosmosoftware.kite.util.TestUtils.kiteServerCommand(TestUtils.java:986)
        at org.webrtc.kite.WebDriverFactory.createWebDriver(WebDriverFactory.java:232)
        at org.webrtc.kite.config.client.Client.createWebDriver(Client.java:482)
        at org.webrtc.kite.tests.TestRunner.initClient(TestRunner.java:82)
        at org.webrtc.kite.tests.TestRunner.<init>(TestRunner.java:71)
        at org.webrtc.kite.tests.TestRunnerCreator.call(TestRunnerCreator.java:33)
        at org.webrtc.kite.tests.TestRunnerCreator.call(TestRunnerCreator.java:12)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

any help would be highly appreciated. also attached clients configuration using inside json config file

"clients": [
    {
      "browserName": "firefox",
      "platform": "localhost",
      "video": {
        "filename": "/IVSAVideoV02",
        "directory": "D:/desktop/Progress/FakeVideos",
        "type": "Video"
      }
    }
  ]

**Comment by RajathTester** [comment]
hi @namvuCosmo  can you please help. I am stuck here any help would be of great value.

Thanks in advance.

**Comment by namvuCosmo** [comment]
Hi,

Can you please provide the steps to reproduce your issue, on how your grid is setup and how your test is launched?

Is KITEServer something you created or something you got from somewhere? Normal run with KITE-Engine shouldn't involve this.

Also, `"filename": "/IVSAVideoV02",` shouldn't have `/` at the beginning.

**Comment by RajathTester** [comment]
Hi @namvuCosmo ,

I am trying to run KiteTest case on a platform developed internally in our company using openvdi.

Steps:
  1. open URL
  2. login to conference room
  3. clicking share webcam
  4. stay in meeting for about 20 seconds

regarding KiteServer, i have not taken it from any where. I simplify install regular KITE2.0 by  following the steps mentioned in https://github.com/webrtc/KITE. Although i was able to run testcases properly with fake video in chrome browser, in firefox i am getting this issues.

Note: I have faced the similar issues when i was running some sample test on openvdi and jitsi platform mentioned in https://github.com/CoSMoSoftware/KITE-Sample-Tests

Below is the image of the cloned repository in my local machine.

![image](https://user-images.githubusercontent.com/57247082/87630040-d6e79100-c751-11ea-877d-46dd12c03123.png)

Thanks in advance.

**Comment by RajathTester** [comment]
Hi,

regarding "/" in filename,  if i donot give it it was not able to get the properly. so i started giving and it was working fine. At least in case of chrome browser that is what i have observerd.

**Comment by RajathTester** [comment]
Hi @namvuCosmo ,

i have going thorugh the code written in webDriverFactory inside the KITEFramework

`  /**
   * Creates a web driver based on the given Client object.
   *
   * @param client           Client
   * @param testName         the test name
   * @param id               an ID to identify the WebDriver
   * @param kiteServerGridId an ID to identify the WebDriver
   * @return WebDriver web driver
   * @throws MalformedURLException if no protocol is specified in the remoteAddress of the client,
   *                               or an unknown protocol is found, or spec is null.
   * @throws WebDriverException    the web driver exception
   */
  public static WebDriver createWebDriver(Client client, String testName, String id, String... kiteServerGridId)
          throws MalformedURLException, WebDriverException, KiteTestException {
    String urlStr = client.getPaas().getUrl();
    logger.debug("createWebDriver on " + urlStr + " for " + client);
    Capability capability = client.getCapability();
    URL url = new URL(urlStr);
    if (!client.isApp()) {
      RemoteWebDriver webDriver = new RemoteWebDriver(url, WebDriverFactory.createCapabilities(client, testName, id));
      if (client.getBrowserSpecs().getBrowserName().equalsIgnoreCase("firefox")) {
        if (capability.useFakeMedia()) {
          if (capability.getVideo() != null || capability.getAudio() != null) {
            String nodePublicIp = new URL(TestUtils.getNode(urlStr, webDriver.getSessionId().toString())).getHost();
            String gridId = kiteServerGridId.length > 0 ? kiteServerGridId[0] : "null";
            String command = writeCommand(capability, client.getBrowserSpecs());
            String uri = "/command?id=" + gridId + "&ip=" + nodePublicIp + "&cmd=" + command;
            logger.debug("kiteServerCommand response:\r\n" + TestUtils.kiteServerCommand(kiteServerUrl, uri));
          }
        }
      }
      return webDriver;
    } else {
      if (client.getBrowserSpecs().getPlatform().name().equalsIgnoreCase("android")) {
        return new AndroidDriver<>(url, WebDriverFactory.createCapabilities(client, testName, id));
      } else if (client.getBrowserSpecs().getPlatform().name().equalsIgnoreCase("ios")) {
        return new IOSDriver<>(url, WebDriverFactory.createCapabilities(client, testName, id));
      } else {
        return new RemoteWebDriver(url, WebDriverFactory.createCapabilities(client, testName, id));
      }
    }
  }
`
i think this where we are getting that log KITEServer, i think this would be help, i think it is beacuase of some gecko driver issues i guess. Any ways i am not sure exactly.

Thanks in advance.

**Comment by namvuCosmo** [comment]
Oh, right. I remember this.

With firefox there''s no flags that we can use to set the fake media, we had to use some other web server on top of it.

Sorry  but I don't think I have a solution for you to use fake media files with firefox right now.

**Comment by RajathTester** [comment]
thank you @namvuCosmo  for the time and help.
