### ISSUE TITLE
Understanding of getPeerConnectionScript() 

### ISSUE THREAD

**Issue by anilkumarjonnalagadda** [webrtc/KITE#150]
Does the same method (getPeerConnectionScript()) helps you in saving peerConnectionObjects in windows.pc variable while working with a conferencing system developed on Kurento SFU

**Comment by anilkumarjonnalagadda** [comment]
hi @namvuCosmo 

Can you please help here ? 

Error is as follows: 
 This is a bug and must be fixed. The exception must be caught and thrown as KiteTestException
   trace = org.openqa.selenium.JavascriptException: javascript error: APP is not defined

**Comment by namvuCosmo** [comment]
Hello,

This function doesn't save the peer connection object as windows.pc variable.

KITE is just using the existing variable for the peer connection object, exposed to browser console level, either it is windows.pc, or something else. This depends on how the developers name it. 
![image](https://user-images.githubusercontent.com/27989546/87892955-07d90600-ca71-11ea-96b6-b576e0c1135e.png)

This doesn't depend on the SFU either.

You can specify it in the config file, example for https://appr.tc:
![image](https://user-images.githubusercontent.com/27989546/87892777-9600bc80-ca70-11ea-8158-b10bdbab7293.png)
