### ISSUE TITLE
Getting error while installing on Ubuntu 20.04

### ISSUE THREAD

**Issue by gharia** [webrtc/KITE#151]
Hi, 

I am trying to install KITE on Ubuntu 20.04. During the `Configure KITE` step, getting below error. And KITE_HOME also not getting set

```
Do you want to start the Grid (y/n)?  y
./setupLocalGrid.sh: line 9: cd: /localGrid: No such file or directory
Setup completed.
./setupLocalGrid.sh: line 14: ./startGrid.sh: No such file or directory

```

**Comment by ss7424Refar** [comment]
I just happened to meet it. My solution is

1. vi /etc/profile
2. export KITE_ HOME = /opt /GitHub/KITE/   (your KITE path)
3. source /etc/profile
4. Re execute  . /configureLinux.sh

**Comment by namvuCosmo** [comment]
Hi,

Sorry for the late reply, I haven't had time to look into this yet. @gharia is the solution @ss7424Refar suggested working for you?

**Comment by gharia** [comment]
Hey @namvuCosmo,

Thanks for asking. I just tried @ss7424Refar suggested solution and I can confirm it worked perfectly fine. Thank you guys for helping. Closing this issue.
