### ISSUE TITLE
Ignore-Certificate-Errors for Google Web Driver

### ISSUE THREAD

**Issue by LexFTW** [webrtc/KITE#154]
I am trying to prepare a test pointing to a URL that does not have the signed SSL certificate, I have read that Google Chrome has a command to avoid blockages called --ignore-certificate-errors, how could you extrapolate it to the web driver?

**Comment by namvuCosmo** [comment]
Hi,

You can try something like this:

```
    {
      "browserName": "chrome",
      "platform": "WINDOWS",
      "version": "84"
      "flags": [
            "ignore-certificate-errors"
      ]
    }
```

Have you tried this flags with normal chrome? 

Also, without SSL, last time I checked, webrtc API for getUserMedia() will not work. Keep this in mind if you're doing stuff with webrtc :)

**Comment by LexFTW** [comment]
Thanks, in my case I was using an unsigned certificate for SSL, but I got this error anyway and I was not figuring out how to fix it, now with this solution you have given me no more problems
