### ISSUE TITLE
Load Testing For Electron App

### ISSUE THREAD

**Issue by ss7424Refar** [webrtc/KITE#155]
Hi! 

It's another question about multiple clients Test that I'm so confused...

Here is the following situations:

1. Electron APP
2. Windows(Platform) can open **only one** `Electron App window` (such as meeting room developed by WebRTC).

How do I simulate multiple clients by using `KITE`.

If there is any good method, please let me know. Thank you !

**Comment by namvuCosmo** [comment]
If one Windows machine (or VM) can open only one electron app, then you will need more machines (or VMs) to simulate more clients.

**Comment by ss7424Refar** [comment]
Hi! 

OK. Thank you for your answer. close the issue.
