### ISSUE TITLE
all the Mac scripts need to be updated for catalina and above (big sur

### ISSUE THREAD

**Issue by agouaillard-cosmo** [webrtc/KITE#166]
The default shell is not bash, it s zsh ....
https://carlosroso.com/the-right-way-to-migrate-your-bash-profile-to-zsh/

**Comment by namvuCosmo** [comment]
do the scripts not work? or is it just a good-to-have modification.

I tried the configureMac script on Big Sur, there was some text displaying glitch to be sorted out but overall the script still works.

**Comment by agouaillard-cosmo** [comment]
It did not work for me because the KITE_HOME variable was not set (it was set in .bashrc which is not read by new shell windows upon opening). Defining this variable in .Zhenv did the trick

**Comment by namvuCosmo** [comment]
I'll try with a completely fresh install factory reset mac on big sur. Since the existing script works most of the time and some other times doesn't, there's no guarantee that changing it to zsh will work 100% of the times either :thinking:

**Comment by agouaillard-cosmo** [comment]
Why not simply writing the env variables in both files (.bashrc and .zhenv) so it would always work?

**Comment by namvuCosmo** [comment]
added zshenv with https://github.com/webrtc/KITE/pull/169
