### ISSUE TITLE
Add console logs to Allure Report using JavaScript

### ISSUE THREAD

**Issue by valdrin123** [webrtc/KITE#174]
How to add console logs to Allure Report by choosing JavaScript for writing test cases ?

Does KITE support that ?

Because for now I can only show in the Allure Report steps and checks through the stepDescription() method.

**Comment by A-nguyenv** [comment]
Hello,
the JS library is not as supported as the Java since we work mostly in Java. Currently, we do not have the bandwith to look into this but will prioritize your problem as soon as possible.

**Comment by nugodu** [comment]
Thank you for your response. For future that'll be fine.

But do you have any solution for this in Java?
If you have one please feel free to share.
