### ISSUE TITLE
Failed to create new test with KITE 

### ISSUE THREAD

**Issue by valdrinnz** [webrtc/KITE#177]
Tried to create a new test with kite_init, there is showing a message Failed to create KITE-TestName-Test

I'm trying with last version.

**Comment by JRuedas** [comment]
> Tried to create a new test with kite_init, there is showing a message Failed to create KITE-TestName-Test
> 
> I'm trying with last version.

The same happens to me. If you check the kite_init script it tries to execute the following command:  _java -cp $KITE_HOME/scripts/init/init.zip Init $1_

Apparently something fails when it is replacing the template elements with the given name.

**Comment by A-nguyenv** [comment]
Hello, 
Thanks for the feedback, there was indeed a problem with the pack.zip, it has been fixed.
Let me know if you still face any issue.

**Comment by valdrinnz** [comment]
Thanks for fixing this issue. 

Now we are able to create new tests with KITE. But when running them in JavaScript there's showing an error "TypeError: Cannot read property 'toLocaleUpperCase' of undefined".

That can be fixed when you go to package.json file and change version of kite-common to 0.1.15

![image](https://user-images.githubusercontent.com/53076997/108818575-e2d5e400-75b9-11eb-8a94-b2d38ee8cde9.png)


Also please fix this syntax error in AppRTC test js.config file. It took me half and our yesterday to figure out why tests aren't running.

![image](https://user-images.githubusercontent.com/53076997/108818683-0ac54780-75ba-11eb-993e-d21a6664d868.png)
