### ISSUE TITLE
Unable to access kite sample tests .Please provide correct url which is having kite sample tests which was mentioned in the README

### ISSUE THREAD

**Issue by ArjunKanamarlapudi** [webrtc/KITE#199]
![image1](https://user-images.githubusercontent.com/69959493/186729541-2a516a02-e8cb-4268-ad43-d10d00b96a51.PNG)

**Comment by ArjunKanamarlapudi** [comment]
Found the tests. Hence closing

**Comment by plok1412** [comment]
Hi, could you please link where you found the tests? Thank you!
