### ISSUE TITLE
README.md doesn't explain what "mvn" is

### ISSUE THREAD

**Issue by alvestrand** [webrtc/KITE#27]
The README.md says that one should do "mvn clean install", but I don't see where the "mvn" command is supposed to come from. Not on my site (which uses OpenJDK 1.8 for its java).

**Comment by jrcosmo** [comment]
I'll correct this, explaining a bit that mvn invokes maven, java build tool.
Thanks for catching this up!

**Comment by alvestrand** [comment]
Apparently Maven needs to be a specific version.
When I did "apt-get install maven", I had an mvn command, but I got this:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project kite-if: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
[ERROR] 

Output of "mvn --version":

hta@hta-hippo:~/code/kite$ mvn --version
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.6.0_41, vendor: Sun Microsystems Inc.
Java home: /usr/lib/jvm/java-6-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-101-generic", arch: "amd64", family: "unix"

**Comment by jrcosmo** [comment]
Java 6 is out of support. Install a recent Java version, as pointed out in the README, like openjdk-8-jdk
