### ISSUE TITLE
"mvn install" fails NoAdapter test

### ISSUE THREAD

**Issue by alvestrand** [webrtc/KITE#43]
Version:
commit accd369aa240a777e358d4e1c499ae32e4d8b552
Merge: d552ca0 cc4300c
Author: Jose M Recio <30715775+jrcosmo@users.noreply.github.com>
Date:   Fri Jan 19 12:14:26 2018 +0800

Reproduce:

mvn install

Results :

Tests in error: 
  org.webrtc.kite.NoAdapterTestTest#testTestScript WebDriverException Reached er...

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] kite-if ............................................ SUCCESS [  1.018 s]
[INFO] kite ............................................... SUCCESS [  5.500 s]
[INFO] apprtc-test ........................................ SUCCESS [ 20.336 s]
[INFO] get-update ......................................... SUCCESS [ 30.006 s]
[INFO] jitsi-test ......................................... SUCCESS [ 33.206 s]
[INFO] noadapter-test ..................................... FAILURE [  8.729 s]
[INFO] kiteweb ............................................ SKIPPED
[INFO] kite-base .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:38 min
[INFO] Finished at: 2018-01-30T09:10:17+01:00
[INFO] Final Memory: 86M/286M
[INFO] ------------------------------------------------------------------------

**Comment by namvuCosmo** [comment]
I'm trying to reproduce it and everything seems OK.

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] kite-if ............................................ SUCCESS [  1.472 s]
[INFO] kite ............................................... SUCCESS [  5.589 s]
[INFO] apprtc-test ........................................ SUCCESS [ 12.710 s]
[INFO] get-update ......................................... SUCCESS [ 31.846 s]
[INFO] jitsi-test ......................................... SUCCESS [ 37.566 s]
[INFO] noadapter-test ..................................... SUCCESS [  7.319 s]
[INFO] kiteweb ............................................ SUCCESS [  1.693 s]
[INFO] kite-base .......................................... SUCCESS [  0.004 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:38 min
[INFO] Finished at: 2018-01-31T12:00:01+08:00
[INFO] Final Memory: 49M/553M
[INFO] ------------------------------------------------------------------------

Did you have the server for NoAdapter test up on localhost:8082 ?

You can do this by going to KITE/KITE-NoAdapter-Test/server, then do:

```
npm install && npm start
```

**Comment by alvestrand** [comment]
Wasn't part of the README, so I missed the need to sart it.

So 2 servers need to be running for the install-time tests to succeed? Why?

**Comment by namvuCosmo** [comment]
The Selenium standalone server needs to be on to spawn the browsers for testing.

The NoAdapter test need it's own server because it tests the simple connection with a node.js based minimal web app and signalling server (without adapter.js). 

The README in of the NoAdapter-Test (https://github.com/webrtc/KITE/tree/master/KITE-NoAdapter-Test) has intructions for the test and how to start the server. We will include it to the  README so there will be no confusion.

**Comment by namvuCosmo** [comment]
Fixed
