### ISSUE TITLE
README.md and Wiki instructions overlap

### ISSUE THREAD

**Issue by alvestrand** [webrtc/KITE#48]
With something as complex as install instructions, if you write it in 2 places, they are going to get out of sync.

The advantage of having them in README.md is that it's version controlled together with the source. The Wiki has its own changelog.

Is it possible to have the instructions sourced in one place (like having an #include on the wiki, or putting "see Wiki" into README.md) rather than duplicating the text?

**Comment by agouaillard-cosmo** [comment]
@alvestrand can you kindly check if it is ok now?

**Comment by ManuCosmo** [comment]
Updated wiki and removed all duplicated/outdated stuffs
