### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [webrtc/KITE#68]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/webrtc/KITE/search?q=0.1-security&unscoped_q=0.1-security

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by namvuCosmo** [comment]
Hi @DanielRuf , 

Thanks for pointing that out. We will look into it and update our code. 

Please let us know if you find anything else that we can improve on.

**Comment by namvuCosmo** [comment]
fixed 5faa4ea2b005e0a2136d47b6ce0a02e9a315707a
