### ISSUE TITLE
I need support for connecting webrtc test with multiple remote ip using kite

### ISSUE THREAD

**Issue by Jayant1907** [webrtc/KITE#70]
How to configure remote ip in kite so i can test webrtc on mutliple remote system.
how can i do that. Please help.

**Comment by ManuCosmo** [comment]
in the test config file, under grids.url, this is the remote (address of the hub)
https://github.com/webrtc/KITE/blob/78ff7da7b8e70c5deac1953feece4b7d75b951bc/KITE-AppRTC-Test/configs/iceconnection.apprtc.config.json#L7

**Comment by Jayant1907** [comment]
i change localhost with remote ip but it not working. Anything else which need to do before running the confige file. Please help !!

**Comment by ManuCosmo** [comment]
If it works on localhost and you have setup a grid with the same browser on a remote IP it should work. there is nothing else to do.
We would need the kite logs and the selenium hub logs as well for further troubleshooting

**Comment by namvuCosmo** [comment]
Closed due to inactivity
