### ISSUE TITLE
error running jitsiTutorial

### ISSUE THREAD

**Issue by M0l1n3ta** [webrtc/KITE#76]
when I try to run jitsiTutorial I've recived this message error

![image](https://user-images.githubusercontent.com/15315199/65053463-47742480-d96c-11e9-96e2-1ad825bd4821.png)

Any idea to solve it???

I've compiled with maven and jdk 11

![image](https://user-images.githubusercontent.com/15315199/65053595-75596900-d96c-11e9-9014-dde52273df45.png)

Best regards
Emilio

**Comment by ManuCosmo** [comment]
Hi Emilio,

KITE requires JDK 8 and is not compatible with JDK 11. You can download JDK 8 at:
https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

Best regards
Emmanuel

**Comment by jpradas** [comment]
Hi, 

I'm having the same issue as Emilio trying to run it in JDK 8. 

![image](https://user-images.githubusercontent.com/7374315/65137835-4db8de00-da0a-11e9-93e1-370c4124a04d.png)

I followed the guide, compiled and tried to run an example like KITE-AppRTC-Test and it went well, but now I can't to use kite_init like Emilio to make an example on my own. 

Regards,
Josué

**Comment by ManuCosmo** [comment]
Indeed. I should have know from the error. The issue was with the init.zip file which was compile for java 8 with the old flag. 
I fixed that. Could you please pull KITE again? you shouldn't need to recompile to use the kite_init script.

**Comment by jpradas** [comment]
Sure it fixed it! I've just pulled and everything's ok. Thank you so much.

Regards,
Josué

**Comment by Piasy** [comment]
Hi CoSMo guys, where could I find the source code of `init.zip`? It's a little bit outdated, the generated code won't compile.
