### ISSUE TITLE
Passing an argument to chrome

### ISSUE THREAD

**Issue by MrVictorBro** [webrtc/KITE#81]
I try to start a chrome node on the remote Linux server.
in order to run chrome on Linux server, chrome needs to pass the argument --no-sandbox.
how can this argument be passed?

**Comment by ManuCosmo** [comment]
Hi Victor,

You can add pass chrome arguments as 'flags' by adding the array to the "client" in the config:


```
"clients": [
    {
      "browserName": "chrome",
      "platform": "localhost",
      "flags": ["--no-sandbox" ]
    }
  ]
```
