### ISSUE TITLE
I need support for connecting parallel remote nodes using kite

### ISSUE THREAD

**Issue by KiteTesting** [webrtc/KITE#84]
I got node connected with a hub and I can run tests from hub to connected nodes (different machines ) one by one, but only with a single user. I need help how to login with different users on different nodes and run these test in parallel nodes, example: in node with port 8888 login with x user and join a call  , while in same time in node with port 9999 login with y user and join the call. 

This is the config file :

{
  "name": "",
  "grids": [
    {
      "type": "local",
      "url": "http://10.0.3.233:4444/wd/hub"
    }
  ],
  "tests": [
    {
      "name": "",
      "tupleSize": 1,
      "description": "",
      "testImpl": "Test.js",
      "payload" : {
        "url":"https://messenger.developershub.info/login",
        "url1":"https://messenger.developershub.info/test/room",
        "user" : 
        {
//here should be multiple usernames and passwords
          "username": "test@hotmail.com",
          "password": "123456"
        }
      }
    }
   
  ],
  "clients": [
     {
   "browserName": "chrome"
  
  }

  
  ]
}

And this is the Login step.The scenario is like this : the user logs in with his own address and then redirects/joins the call link:

const { TestStep, TestUtils } = require('kite-common');
class LoginStep extends TestStep {
    constructor(kiteBaseTest) {
        super();
        this.driver = kiteBaseTest.driver;
        this.timeout = kiteBaseTest.timeout;
        this.url = kiteBaseTest.payload.url;
        this.url1 = kiteBaseTest.payload.url1;
        this.uuid = kiteBaseTest.uuid;
        this.page = kiteBaseTest.page;
        this.id = kiteBaseTest.id;
        this.user = kiteBaseTest.payload.user.username;
        this.pass = kiteBaseTest.payload.user.password;
    }

    stepDescription() {
        return 'Login at: ' + this.url + ' as guest: ' +  this.user;
    }
    async step() {
        
        await this.page.open(this);
        await this.page.enterEmail(this.user);
        await this.page.enterPassword(this.pass);
    }
}

module.exports = LoginStep;

**Comment by namvuCosmo** [comment]
Hi, so there are a few things you can add to your test:
 - tupleSize": 1 -> 2 (or N, depends on the number of participants you need)
 - user in payload can then be an array of users that can be assigned to runners.
 - you then can use `this.id = kiteBaseTest.id;` to get users[id] from the payload and use the username and password to sign in on different nodes.

We do have a similar test with Hangout that you can take a look here:
https://github.com/CoSMoSoftware/KITE-Sample-Tests/tree/master/KITE-Hangouts-Test

Let me know how it turns out :)

**Comment by namvuCosmo** [comment]
Glad I could help
