### ISSUE TITLE
How to run KITE test in Docker Swarm ?

### ISSUE THREAD

**Issue by KiteTesting** [webrtc/KITE#87]
I have installed KITE locally, and I can run KITE tests from hub to nodes (different machines, same network) by this configuration:
 Config file of the project:
{
  "name": "MessengerLogin %ts",
  "grids": [
    {
   
      "type": "local",

       "url": "http://10.0.0.71:4444/wd/hub"
    }.......
       }
      }
    }
  ],
  "clients": [
     {
   "browserName": "chrome",
   "PLATFORM" : "LINUX"
  
  }
  

Hub configuration:
@echo off 
setlocal 
  title Hub 
  java -jar ../selenium.jar -role hub --debug -host ipAddress
endlocal 
pause 

Node configuration:
java -Dwebdriver.chrome.driver=./chromedriver.exe -jar ../selenium.jar -role node -maxSession 10 -port xyz -host ipAddress -hub http://ipAddress:port/grid/register  -browser browserName=chrome,maxInstances=10 --debug  

Now I need to do same work but through Docker Swarm (not locally) https://prnt.sc/psly63 . So , I am able to create grid through yml file in swarm:
version: "3.7"

networks:
  main:
    driver: overlay
services:
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    networks:
      - main
    deploy:
      mode: replicated
      replicas: 1
      labels:
        selenium.grid.type: "hub"
        selenium.grid.hub: "true"
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == worker]
  chrome:
    image: selenium/node-chrome-debug
    entrypoint: >
      bash -c '
        export IP_ADDRESS=$$HOSTNAME &&
        SE_OPTS="-host $$IP_ADDRESS" /opt/bin/entry_point.sh'
    volumes:
      - /dev/urandom:/dev/random
      - /dev/shm:/dev/shm
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 1
    networks:
      - main
    deploy:
      mode: replicated
      replicas: 3
      labels:
        selenium.grid.type: "node"
        selenium.grid.node: "true"
        selenium.grid.node.type: "chrome"
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == worker]
  firefox:
    image: selenium/node-firefox
    entrypoint: >
      bash -c '
        export IP_ADDRESS=$$HOSTNAME &&
        SE_OPTS="-host $$IP_ADDRESS" /opt/bin/entry_point.sh'
    volumes:
      - /dev/shm:/dev/shm
      - /dev/urandom:/dev/random
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 1
    networks:
      - main
    depends_on:
      - hub
    deploy:
      mode: replicated
      replicas: 3
      labels:
        selenium.grid.type: "node"
        selenium.grid.node: "true"
        selenium.grid.node.type: "firefox"
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == worker]

Now, my question is how can i integrated KITE tests to be run in swarm, cuz when i hit run https://prnt.sc/psm609 , it shows me this https://prnt.sc/psm6l5

**Comment by ManuCosmo** [comment]
Hi,

What do you see when you open http://10.0.0.71:4444/grid/console in your browser?
There needs to be at least on Chrome on OS LINUX.

**Comment by KiteTesting** [comment]
@Emmanuel ,  http://10.0.0.71:4444 is the grid ip that i set up on Docker Swarm, 10.0.0.71 is the manager node ip and 4444 is the port. When i open this in browser it shows me connected nodes , but i cannot run kite tests on them   https://prnt.sc/psly63  : 

![image](https://user-images.githubusercontent.com/54436573/68195886-01286280-ffb8-11e9-97a4-af3e83c7815a.png)

**Comment by ManuCosmo** [comment]
It should be working. Do you confirm the clients is LINUX?

```
"clients": [
{
"browserName": "chrome",
"PLATFORM" : "LINUX"

}
```

**Comment by KiteTesting** [comment]
closed
