### ISSUE TITLE
How to compile and run KITE test in Linux ?

### ISSUE THREAD

**Issue by KiteTesting** [webrtc/KITE#88]
Im about to start writing KITE tests in Linux. This is the Dockerfile i created:

FROM ubuntu as KiteBase

RUN apt update 
RUN apt install -y default-jre default-jdk openjdk-8-jdk maven git gcc build-essential
RUN git clone https://github.com/webrtc/KITE.git KITE

WORKDIR /KITE/scripts/linux

RUN chmod +x *.sh ./setupLocalGrid.sh

COPY ./utils/google-chrome.list /etc/apt/sources.list.d/google-chrome.list

RUN apt install wget -y
RUN wget https://dl.google.com/linux/linux_signing_key.pub
RUN apt-key add linux_signing_key.pub
RUN apt update
RUN apt install google-chrome-stable -y
RUN apt install npm  nodejs -y
RUN nodejs -v

ENV KITE_HOME=/KITE
ENV MAVEN_HOME =/usr/share/maven
ENV JAVA_HOME =/usr/share/Java

FROM KiteBase 

COPY ./scripts/linux/setupLocalGrid.sh .

COPY ./KITE-Example-Test .

I am able to create the localgrid in linux like this:

![image](https://user-images.githubusercontent.com/54436573/68478845-2f64a700-0231-11ea-9f50-aeea305a175a.png)

Im able to go into the project folder like in the picture below :

![image](https://user-images.githubusercontent.com/54436573/68478459-350dbd00-0230-11ea-8136-f7d95a9f5e11.png)

Now I'm asking if i should at first compile the project and then run it ?! If yes, how can I do the compiling and running the project, because the commands provided in this tutorial are not working :

![image](https://user-images.githubusercontent.com/54436573/68478595-95046380-0230-11ea-85e3-f4cc28303f44.png)

Thanks!

**Comment by namvuCosmo** [comment]
Hi,
After cloning KITE, you can run our configuring scripts (depends on your OS):
 - configureLinux.sh
 - configure.bat
 - configureMac.sh

This will set the env variables for KITE, including the path to the scripts (KITE/scripts/os/path/) for:
 - c : compiling
 - r : run 
 - a : open allure report (kite-allure-reports)

After this you can use the commands in the tutorials. We do recommend you running the configure script, but alternatively, you can use these followings:
 - Compile: `mvn -DskiptTests clean install`
 - Run: `java (-Dkite.firefox.profile="PATH_TO_FIREFOX_PROFILE) -cp PATH_TO_KITE/KITE-Engine/target/kite-jar-with-dependencies.jar:PATH_TO_TEST/target:*" org.webrtc.Engine PATH_TO_CONFIG_FILE`
 - Allure report: allure serve PATH_TO_ALLURE_REPORT

*Firefox profile is optional, however, we do provide a default profile with h264 plugin pre-installed, this might be needed for some WebRTC application.
**For classpath, on Linux and Mac, the jars are separated by ":", and on Windows by ";"

Cheers,

**Comment by KiteTesting** [comment]
I did all the instructions you said and i copied the project , and now I want to run the KITE-Example test, but im stucked with this error :

![image](https://user-images.githubusercontent.com/54436573/68597089-a651a800-049c-11ea-89ca-1fb007d44eec.png)


![image](https://user-images.githubusercontent.com/54436573/68597135-bc5f6880-049c-11ea-8191-6c324f8fca7c.png)



![image](https://user-images.githubusercontent.com/54436573/68597157-c4b7a380-049c-11ea-9027-5497b6a1612a.png)


![image](https://user-images.githubusercontent.com/54436573/68597189-d436ec80-049c-11ea-8b42-e17664da9931.png)

**Comment by namvuCosmo** [comment]
Did you compile the KITE Engine before cd into KITE-Example-Test and call `c`?

If you already call `c` int KITE/, it compiles all of the modules including KITE-Example-Test, there's no need to compile the test module individually unless you're making changes to it.

After that you can just call `r` to run your test.

**Comment by KiteTesting** [comment]
When im trying to compile the entire KITE folder , it is showing this :


![image](https://user-images.githubusercontent.com/54436573/68662534-4828d180-053d-11ea-9e8c-f2de7eca9a02.png)

**Comment by namvuCosmo** [comment]
I'm trying to reproduce your errors, but can't. This is on a virtual machine with Ubuntu 18.04, maybe you're using a different variation of Linux?

![image](https://user-images.githubusercontent.com/27989546/68747337-47736680-0635-11ea-88cc-d3caca0178e3.png)

Java and Maven version: 
![image](https://user-images.githubusercontent.com/27989546/68747443-843f5d80-0635-11ea-9b9e-5abc9e4a063c.png)

**Comment by KiteTesting** [comment]
This is the docker file im working with :

FROM ubuntu as KiteBase

RUN apt update 
RUN apt install -y default-jre default-jdk openjdk-8-jdk maven git gcc build-essential nodejs npm 

RUN apt-get install -y wget
RUN wget https://dl.google.com/linux/linux_signing_key.pub


#KITE
RUN git clone https://github.com/webrtc/KITE.git KITE
#RUN mvn --version
#RUN java --version
#WORKDIR /KITE/
#RUN chmod +x *.sh ./configureLinux.sh
WORKDIR /KITE/scripts/linux
RUN chmod +x *.sh ./setupLocalGrid.sh

COPY ./utils/google-chrome.list /etc/apt/sources.list.d/google-chrome.list

RUN apt install wget -y
RUN wget https://dl.google.com/linux/linux_signing_key.pub
RUN apt-key add linux_signing_key.pub
RUN apt update
RUN apt install google-chrome-stable -y
#RUN apt install npm  nodejs -y


ENV KITE_HOME=/KITE
ENV JAVA_HOME =/usr/lib/jvm/java-11-openjdk-amd64
RUN export JAVA_HOME
ENV MAVEN_HOME =  /usr/share/maven
RUN export MAVEN_HOME
FROM KiteBase 

COPY ./scripts/linux/setupLocalGrid.sh .
COPY ./scripts/linux/gridConfig.sh .
COPY ./scripts/linux/path/* ./
#COPY ./scripts/linux/path/c .
#COPY ./scripts/linux/path/r .
#COPY ./scripts/linux/path/t .
#COPY ./scripts/linux/path/a .
#COPY ./scripts/linux/path/kite_init .
COPY ./KITE-Example-Test/* ./


Im still able to launch the grid :

![image](https://user-images.githubusercontent.com/54436573/68753360-2eeb5800-0605-11ea-93b1-155fe77ef5d5.png)



While, when i try to compile KITE or any project or check the maven version im getting this error :

![image](https://user-images.githubusercontent.com/54436573/68753410-46c2dc00-0605-11ea-993c-ffd5b368dcd8.png)

**Comment by namvuCosmo** [comment]
I can't really help if I can't reproduce the issue here. 

I followed your set of commands in both of your docker files and I got:
- Java 11, maven 3.6 (my previous comment)
- Java 8, maven 3.3.9 :
![image](https://user-images.githubusercontent.com/27989546/68825532-6295b300-06d5-11ea-9b49-975f43e67e0b.png)

For me, on Ubuntu 18.04, these commands should be enough to compile KITE:
```
sudo apt-get install git openjdk-8-jdk maven
git clone https://github.com/webrtc/KITE KITE
cd KITE
cp scripts/linux/path/* ./ (if you don't want to add this to you $PATH)
./c 
```

Which variation of LINUX are you using?

**Comment by KiteTesting** [comment]
But probably it should be an alternative to run tests or to recognize the 'r' command :

![image](https://user-images.githubusercontent.com/54436573/68871641-0d6d9780-06fd-11ea-9e16-897766cf65c8.png)



FROM ubuntu as KiteBase

RUN apt update 
RUN apt install -y default-jre default-jdk openjdk-8-jdk maven git gcc build-essential nodejs npm 

RUN apt-get install -y wget
RUN wget https://dl.google.com/linux/linux_signing_key.pub


#KITE
RUN git clone https://github.com/webrtc/KITE.git KITE
RUN mvn --version
RUN java --version
#WORKDIR /KITE/
#RUN chmod +x *.sh ./configureLinux.sh
WORKDIR /KITE/scripts/linux
RUN chmod +x *.sh ./setupLocalGrid.sh

COPY ./utils/google-chrome.list /etc/apt/sources.list.d/google-chrome.list

RUN apt install wget -y
RUN wget https://dl.google.com/linux/linux_signing_key.pub
RUN apt-key add linux_signing_key.pub
RUN apt update
RUN apt install google-chrome-stable -y



ENV KITE_HOME=/KITE
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64

RUN export JAVA_HOME=/opt/java/jdk-11.0.1
RUN export PATH=$PATH:$JAVA_HOME/bin
ENV MAVEN_HOME  /opt/maven
RUN export MAVEN_HOME



FROM KiteBase 

COPY ./scripts/linux/setupLocalGrid.sh .
COPY ./scripts/linux/gridConfig.sh .
COPY ./scripts/linux/path/c .
COPY ./scripts/linux/path/r .
COPY ./scripts/linux/path/t .
COPY ./scripts/linux/path/a .
COPY ./scripts/linux/path/kite_init .

#WORKDIR /KITE-Example-Test .
#COPY ./KITE-Example-Test .

**Comment by namvuCosmo** [comment]
There is of course, the r command is just a quick way to do it instead of:
```
java (-Dkite.firefox.profile="PATH_TO_FIREFOX_PROFILE") (-Dkite.chrome.extension="PATH_TO_CHROME_EXTENSION")  -cp "PATH_TO_kite-jar-with-dependencies.jar:PATH_TO_YOUR_TEST_JAR" org.webrtc.kite.Engine PATH_TO_YOUR_CONFIG_FILE
```

 - any (...) is optional
 - kite-jar-with-dependencies.jar is normally at KITE/KITE-Engine/target after compiling 
 - your test jar is normally in the target folder of your test folder
 - on windows, to separate classpath, it's ";" instead of ":"

**Comment by tmatth** [comment]
@KiteTesting can you share your actual docker commands (`docker build` etc.)

**Comment by tmatth** [comment]
FWIW I was able to build the image with your Dockerfile with this modification:
```
FROM ubuntu:bionic-20191029 as KiteBase
```
and
```
KITE$ cat utils/google-chrome.list 
### THIS FILE IS AUTOMATICALLY CONFIGURED ###
# You may comment out this entry, but any other modifications may be lost.
deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
```

**Comment by KiteTesting** [comment]
I've been able at first to launch the grid, then to compile and run the project in nodes 

![image](https://user-images.githubusercontent.com/54436573/70802815-c8e42300-1db2-11ea-89fc-ec4cbcb51dd9.png)


But I keep getting those erros about webdriver, any help about that ?

This is the dockerfile im using :

FROM ubuntu:bionic-20191029 as KiteBase

RUN apt update 
RUN apt install -y default-jre default-jdk openjdk-8-jdk maven git gcc build-essential nodejs npm 
RUN apt-get install nano -y 
RUN apt-get install -y wget 
RUN wget https://dl.google.com/linux/linux_signing_key.pub



#KITE
RUN git clone https://github.com/webrtc/KITE.git KITE
RUN mvn --version
RUN java --version
WORKDIR /KITE/

WORKDIR /KITE/
RUN chmod +x *.sh ./configureLinux.sh

COPY ./utils/google-chrome.list /etc/apt/sources.list.d/google-chrome.list

RUN wget https://dl.google.com/linux/linux_signing_key.pub
RUN apt-key add linux_signing_key.pub
RUN apt update
RUN apt install google-chrome-stable -y



ENV KITE_HOME=/KITE
RUN export KITE_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

RUN export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/bin
#RUN export PATH=$PATH:$JAVA_HOME/bin
ENV MAVEN_HOME=/opt/maven
RUN export MAVEN_HOME



FROM KiteBase 
COPY ./KITE-Engine .
COPY ./KITE-Framework .
COPY ./KITE-Engine .
COPY ./scripts/linux/setupLocalGrid.sh .
COPY ./scripts/linux/gridConfig.sh .
COPY ./scripts/linux/path/c .
COPY ./scripts/linux/path/r .
COPY ./scripts/linux/path/t .
COPY ./scripts/linux/path/a .
COPY ./scripts/linux/path/kite_init .
ADD pom.xml /KITE/pom.xml

#WORKDIR ./KITE-Engine .
#COPY ./KITE-Engine .

WORKDIR KITE/KITE-MessengerLogin-Test .
COPY ./KITE-MessengerLogin-Test .

**Comment by namvuCosmo** [comment]
Hi, I'll try to reproduce that error with Js test next week and get back to you. Normally if your grid has chrome on linux, there should not be this error.

However we are not currently using docker, so I will test it only with ubuntu 18.

**Comment by KiteTesting** [comment]
Now, with this version of dockerfile, im getting this error:

FROM ubuntu as KiteBase

RUN apt update 
RUN apt install -y default-jre default-jdk openjdk-8-jdk maven git gcc build-essential nodejs npm 
RUN apt-get install nano -y 
RUN apt-get install -y wget dpkg unzip 

#KITE
RUN git clone https://github.com/webrtc/KITE.git KITE
RUN mvn --version
RUN java --version

WORKDIR /KITE/

RUN chmod +x *.sh ./configureLinux.sh

ENV KITE_HOME=/KITE
RUN export KITE_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

RUN export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/bin
#RUN export PATH=$PATH:$JAVA_HOME/bin
ENV MAVEN_HOME=/usr/share/maven
RUN export MAVEN_HOME



FROM KiteBase 
COPY ./KITE-Engine .
COPY ./KITE-Framework .
COPY ./KITE-Engine .
COPY ./scripts/linux/setupLocalGrid.sh .
COPY ./scripts/linux/gridConfig.sh .
COPY ./scripts/linux/path/c .
COPY ./scripts/linux/path/r .
COPY ./scripts/linux/path/t .
COPY ./scripts/linux/path/a .
COPY ./scripts/linux/path/kite_init .
COPY ./scripts/linux/createFolderLocalGrid.sh .
COPY ./scripts/linux/installChrome.sh .
COPY ./scripts/linux/installFirefox.sh .
COPY ./scripts/linux/installSelenium.sh .
COPY ./scripts/linux/installMaven.sh .
COPY ./scripts/linux/interactiveInstallation.sh .





ADD pom.xml /KITE/pom.xml

WORKDIR KITE/KITE-MessengerLogin-Test .
COPY ./KITE-MessengerLogin-Test .


Check the errors here https://prnt.sc/qg0j6n      https://prnt.sc/qg0jfj      https://prnt.sc/qg0kd9

I know the errors are about the drivers versions, but could you help us a little here ?

**Comment by namvuCosmo** [comment]
It looks like the error is due to the connection to the hub, the localhost  address is not reachable for KITE.

**Comment by KiteTesting** [comment]
FROM ubuntu as KiteBase

RUN apt update 
RUN apt install -y default-jre default-jdk openjdk-8-jdk maven git gcc build-essential 
RUN apt-get install nano -y 
RUN apt-get install -y sudo wget dpkg unzip xvfb

#KITE
RUN git clone https://github.com/webrtc/KITE.git KITE
RUN mvn --version
RUN java --version

WORKDIR /KITE/


     

RUN chmod +x *.sh ./configureLinux.sh

ENV KITE_HOME=/KITE
RUN export KITE_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

RUN export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/bin
#RUN export PATH=$PATH:$JAVA_HOME/bin
ENV MAVEN_HOME=/usr/share/maven
RUN export MAVEN_HOME



FROM KiteBase 
COPY ./KITE-Engine .
COPY ./KITE-Framework .
COPY ./KITE-Engine .
COPY ./scripts/linux/setupLocalGrid.sh .
COPY ./scripts/linux/gridConfig.sh .
COPY ./scripts/linux/path/c .
COPY ./scripts/linux/path/r .
COPY ./scripts/linux/path/t .
COPY ./scripts/linux/path/a .
COPY ./scripts/linux/path/kite_init .
COPY ./scripts/linux/createFolderLocalGrid.sh .
COPY ./scripts/linux/installChrome.sh .
COPY ./scripts/linux/installFirefox.sh .
COPY ./scripts/linux/installSelenium.sh .
COPY ./scripts/linux/installMaven.sh .
COPY ./scripts/linux/installDrivers.sh .
COPY ./scripts/linux/interactiveInstallation.sh .






ADD pom.xml /KITE/pom.xml

WORKDIR KITE/KITE-Login-Test .
COPY ./KITE-Login-Test .


From this dockerfile i launch the grid by this command RUN chmod +x *.sh ./configureLinux.sh .



the script installChrome.sh::
#!/bin/bash
set +v
. ./gridConfig.sh
google-chrome-stable -version >chrome.txt
chromeFile="chrome.txt"
chrome=$(cat "$chromeFile")


if [[ $chrome == *$CHROME_VERSION* ]]; then
  echo Chrome version $CHROME_VERSION was found
else
  echo Chrome version $CHROME_VERSION was not found, installing it.
  
   wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
   dpkg -i google-chrome-stable_current_amd64.deb
   apt-get fonts-liberation
   apt --fix-broken install
  rm -f google-chrome-stable_current_amd64.deb
fi

rm -f chrome.txt

exit



the script setupLocalGrid.sh :

#!/bin/bash
set +v
. ./gridConfig.sh

echo $KITE_HOME
cd $KITE_HOME/scripts/linux



function startGrid() {
  cd $KITE_HOME/localGrid
  if [ "$DESKTOP_ENVIRONMENT" = "TRUE" ]
  then
    x-terminal-emulator -e ./startGrid.sh &
  else
    ./startGrid.sh &
  fi
}

if [[ "$DESKTOP_ENVIRONMENT" = "TRUE" ]]
then
apt-get -y upgrade -f gnome-terminal
fi

./createFolderLocalGrid.sh

if [[ "$INSTALL_BROWSERS" = "TRUE" ]]
then
  ./installChrome.sh
  ./installFirefox.sh
else
  echo "Skipping Chrome and Firefox installation"
fi

./installDrivers.sh
./installSelenium.sh

#read -p "Do you want to start the Grid (y/n)?  " yn
 #case $yn in
  #         startGrid
   #         ;;
    # [Nn]* )
     #      echo " "
      #     ;;
     #* ) echo "Please answer yes or no.";;
 #esac

#startGrid


echo "Setup completed."




gridConfig.sh script:

#!/bin/bash
# Grid setup configuration for Ubuntu
#
# Please check the Firefox and Chrome versions installed on your computer. If none installed, this script will download and install them.
#
# Please check and update the corresponding chromedriver and geckodriver versions from:
# http://chromedriver.chromium.org/downloads
# https://github.com/mozilla/geckodriver/releases
#
# Please check the selenium version from: https://selenium-release.storage.googleapis.com/


# Set to TRUE to install Chrome and Firefox, or FALSE to skip this step if the correct versions are already installed.
export INSTALL_BROWSERS=TRUE

# Set to TRUE/FALSE to enable/disable the CAPABILITY MATCHER
export USE_CAPABILITY_MATCHER=FALSE

# Set to TRUE if this is a full desktop environment, FALSE if it's without any display
export DESKTOP_ENVIRONMENT=FALSE

# Set to TRUE to use localhost or FALSE to use the host's IP address
export LOCALHOST=FALSE

# ChromeDriver and GeckoDriver versions
export GECKO_VERSION=v0.26.0
export CHROMEDRIVER_VERSION=79.0.3945.36


# Selenium version
export SELENIUM_VERSION_SHORT=3.141
export SELENIUM_VERSION=3.141.59

# Browser versions
export FIREFOX_VERSION=70
export CHROME_VERSION=79

#Capability Matcher
export KITE_EXTRAS_VERSION=0.1.4
export GRID_UTILS_VERSION=0.0.1

**Comment by namvuCosmo** [comment]
And on the grid's console UI (http://HUB_IP:HUB_PORT/grid/console), do you have all the browsers listed, with the correct config that you're calling ?
Something like this: (never mind the gateway and binary path)
![image](https://user-images.githubusercontent.com/27989546/72124598-59a52300-33a0-11ea-8277-7890342d0abb.png)

![image](https://user-images.githubusercontent.com/27989546/72124622-6b86c600-33a0-11ea-9ffe-77a9712384c3.png)

and same for firefox

**Comment by KiteTesting** [comment]
Im testing only with Chrome and this is what i get :

![image](https://user-images.githubusercontent.com/54436573/72137729-a0d4e900-338b-11ea-94be-7af64fd44a03.png)

**Comment by namvuCosmo** [comment]
Looks like you do have a node registered with chrome 79.
Does you config file look like this, for the grid and clients?
![image](https://user-images.githubusercontent.com/27989546/72138384-afd98c80-33c7-11ea-876d-4c8036875183.png)

Can the machine/container on which you're running KITE connect to `http://172.17.0.2:4444/wd/hub`

Please provide the exact info that I require and make sure that your comments are easy to read.
It seems that every time you are providing a lot of  irrelevant stuff which make it difficult to understand your process and to resolve your issue.

**Comment by KiteTesting** [comment]
![image](https://user-images.githubusercontent.com/54436573/72143632-578a9680-3397-11ea-800c-503828db9961.png)




![image](https://user-images.githubusercontent.com/54436573/72143651-5eb1a480-3397-11ea-9c8e-12faceeff924.png)

**Comment by KiteTesting** [comment]
issue is solved

**Comment by Lazarus404** [comment]
@KiteTesting what was your eventual Dockerfile?  I have built one myself, but I can't seem to get Chrome to run headless.
