### ISSUE TITLE
How do I stop KITE in sending fake media ?

### ISSUE THREAD

**Issue by rsharma0824** [webrtc/KITE#90]
HI,

How do I stop the KITE in sending the fake Video streaming ?Whenever I run the test,KITE is sending a fake video.
I don't want the fake media streaming  during my test run.Please advise

**Comment by namvuCosmo** [comment]
Hi,

You can choose not to send fake media as follow :
```
    {
      "browserName": "chrome",
      "version": "80",
      "platform": "WINDOWS",
      "headless": false,
      "useFakeMedia": false,
      "exclude": false
    }
```

**Comment by rsharma0824** [comment]
Thank you @namvuCosmo ..Can you please redirect me to the file which has the above information?There are lot of config files in the KITE folder ,but I am not sure which file to update?

**Comment by namvuCosmo** [comment]
In all of these config files ( like [this one](https://github.com/webrtc/KITE/blob/master/KITE-Example-Test/configs/auth.local.config.json)) you should see a `clients` section that contains the browsers/apps configurations that you want to run your test with and you can modify them like I mentioned in my previous comment to not send fake media.

If you want to dive into the code to see where these parameters are used, take a look at these classes in our Framework module :
 - [Client class](https://github.com/webrtc/KITE/blob/master/KITE-Framework/src/main/java/org/webrtc/kite/config/client/Client.java)
 - [WebDriverFactory class](https://github.com/webrtc/KITE/blob/master/KITE-Framework/src/main/java/org/webrtc/kite/WebDriverFactory.java)

**Comment by namvuCosmo** [comment]
close due to inactivity
