### ISSUE TITLE
Save logs in database

### ISSUE THREAD

**Issue by KiteTesting** [webrtc/KITE#94]
Im getting webrtc stats in this way :

"getStats": {
          "enabled": true,
          "statsCollectionTime": 2,
          "statsCollectionInterval": 1,
          "peerConnections": [ "window.peerConnections[0]" ],
          "selectedStats": [ "inbound-rtp", "outbound-rtp", "candidate-pair", 
          "local-candidate" , "remote-candidate" ,"stream","peer-connection","codec","track" , "transport"
          ]
        }
      }

And im getting logs and other reports generated after test execution . I want to know is there a way how can I store those logs/allure reports directly to a database or a server , or they can be saved only locally ?

**Comment by namvuCosmo** [comment]
For now they are saved locally only. You will need to process them as you like after test execution.

**Comment by KiteTesting** [comment]
Ok thanks. And from these all of these webrtc statistics i get in allure reports, i cannot find anything about the received video resolution or bandwidth, which of these statistics tell these details and how can i read them :

![image](https://user-images.githubusercontent.com/54436573/72138281-d0d0bc00-338c-11ea-9d02-c83eb352e424.png)

**Comment by KiteTesting** [comment]
issue is solved
