### ISSUE TITLE
Can you run all test cases you have in config folder, with one command ? 

### ISSUE THREAD

**Issue by valdrinnz** [webrtc/KITE#95]
In my case I have three tests in config folder like this: 

If you want to run first test you just go to folder which is your test and type: r config\js.yourfirsttest.json
and for the second test: r config\js.yoursecondtest.json

But I want to run all the tests with one command, is that possible in KITE ?

**Comment by namvuCosmo** [comment]
Hi,

Sorry but currently it's not possible, I'll think about including this in our next update.

**Comment by namvuCosmo** [comment]
Implemented

**Comment by valdrinnz** [comment]
Can u please tell us which is that command ?

**Comment by namvuCosmo** [comment]
Oh sorry I misunderstood the issue. You still can't use PATH_TO_DIRECTORY to run all config files inside, but you can put multiple files as parameters to run.

**Comment by namvuCosmo** [comment]
Hi @valdrinnz , I added the code to run with the whole directory.

You can either:

- Call the command `r`, it will run the whole `configs` folder, or `r DIRECTORY_NAME`, it will run the `configs\DIRECTORY_NAME` directory

It should also find all the test.json in the sub-folders as well, so your folder can be:
```
tests/
|-- test0.json
|-- TS1/
|    |-- test1.json
|    |-- test2.json
|-- TS2/
|    |-- test3.json
|    |-- test4.json
|....
```

- Call the java command to run the engine directly:
windows:
```
java -Dkite.firefox.profile="%KITE_HOME%"/third_party/firefox-h264-profiles/ -cp "%KITE_HOME%/KITE-Engine/target/kite-jar-with-dependencies.jar;target/*" org.webrtc.kite.Engine PATH_TO_YOUR_DIRECTORY
```

linux/mac:
```
java -Dkite.firefox.profile="$KITE_HOME"/third_party/firefox-h264-profiles/ -cp "$KITE_HOME/KITE-Engine/target/kite-jar-with-dependencies.jar:target/*" org.webrtc.kite.Engine configs/iceconnection.apprtc.config.json
```

Let me know if you have any issue

**Comment by valdrinnz** [comment]
This is nice feature ! I'm gonna try it as soon as I get last version, it should work fine. Thank you for your response.
