### ISSUE TITLE
 org.openqa.selenium.JavascriptException: javascript error: APP is not defined

### ISSUE THREAD

**Issue by liwei721** [webrtc/KITE#99]
I ran into a problem with CentOS when executing scripts，Can someone help me?

**Comment by liwei721** [comment]
![image](https://user-images.githubusercontent.com/3367699/75862485-000a2380-5e3a-11ea-860f-40c4c77b5a66.png)
It seems to have something to do with this problem，

**Comment by namvuCosmo** [comment]
Hello,

I'm sorry but currently we don't have the capacity to maintain our JS library.

But thanks for your issue, we'll investigate in the future.
